workflows:
  android-app:
    name: Build BoostPro
    environment:
      vars:
        JAVA_VERSION: 17
      android_signing:
        keystore: false
    scripts:
      - name: Use Codemagic’s Gradle
        script: echo "Using Codemagic system Gradle"
      - name: Build APK
        script: ./gradlew assembleDebug || gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
