workflows:
  debug-android:
    name: Debug Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      android_signing:
        - debug_keystore

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Build Debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
